prison:
  location: spawn, -5.700, 85.227, -1237.438
  lines:
  - '&c&l&nPrison'
  - '&b&lEnter at your own'
  - '&4&l&nRISK!'
moon:
  location: spawn, 34.700, 84.000, -1237.487
  lines:
  - '&l&nThe Moon'
  - '&4&lPVP &5&l& &4&lGreifing allowed'
plots:
  location: spawn, 14.529, 84.605, -1256.700
  lines:
  - '&l&nPlot World'
  - '&e&lWatch Out For Mobs!!'
loveyou:
  location: spawn, 14.505, 94.000, -1237.484
  lines:
  - '&4<3'
donor:
  location: spawn, 14.535, 84.200, -1212.006
  lines:
  - '&lDonor Ranks'
suggestions1:
  location: spawn, -6.585, 84.000, -1241.579
  lines:
  - '&uSuggestions'
suggestions2:
  location: spawn, -6.521, 84.000, -1233.448
  lines:
  - '&uSuggestions'
playershops:
  location: spawn, 33.767, 85.000, -1256.768
  lines:
  - '&d&l Player Shops'
mine:
  location: spawn, 31.513, 84.000, -1220.420
  lines:
  - '&u&lStarter Mine'
crate1:
  location: spawn, 6.591, 85.075, -1232.509
  lines:
  - '&u&lRewards Chest'
  - Opens with Vote & Badass keys
  - '&b&l/Vote &rfor prizes!'
crate2:
  location: spawn, 6.490, 85.075, -1242.507
  lines:
  - '&u&lRewards Chest'
  - Opens with Vote & Badass keys
  - '&b&l/Vote &rfor prizes!'
petshop:
  location: spawn, 247.498, 112.739, -1214.514
  lines:
  - '&b&lPet Shop'
junkyard:
  location: spawn, 248.124, 109.386, -1273.504
  lines:
  - '&2&lJunk Yard'
blackmarket:
  location: spawn, 209.509, 101.491, -1377.588
  lines:
  - '&0&lBlack Market'
orchard:
  location: spawn, 83.654, 103.123, -1306.536
  lines:
  - '&c&lOrchard'
farmtown:
  location: spawn, 88.315, 111.815, -1353.303
  lines:
  - '&e&lFarmtown'
library:
  location: spawn, 76.444, 94.700, -1184.800
  lines:
  - '&e&lLibrary'
claymine:
  location: spawn, 79.300, 114.999, -1409.300
  lines:
  - '&u&lClay Mine'
welcome:
  location: spawn, -71.539, 86.200, -1153.730
  lines:
  - '&b&lRock &c&lDiamond &rPrison'
  - Welcomes you !!!
zombiefarm:
  location: spawn, -141.516, 98.200, -1169.782
  lines:
  - '&4&lZombie Farm'
xpfarm:
  location: spawn, -186.332, 98.287, -1275.533
  lines:
  - '&uExperience Farm'
