prison:
  location: spawn, -5.700, 85.227, -1237.438
  lines:
  - '&c&l&nPrison'
  - '&b&lEnter at your own'
  - '&4&l&nRISK!'
moon:
  location: spawn, 34.700, 84.000, -1237.487
  lines:
  - '&l&nThe Moon'
  - '&4&lPVP &5&l& &4&lGreifing allowed'
  - '&4&lFactions Here!'
plots:
  location: spawn, 14.529, 84.605, -1256.700
  lines:
  - '&l&nPlot World'
  - '&e&lWatch Out For Mobs!!'
loveyou:
  location: spawn, 14.505, 94.000, -1237.484
  lines:
  - '&4<3'
parkour:
  location: spawn, -6.365, 85.355, -1219.490
  lines:
  - '&b&l&nParkour!'
  - '&b&lTest out your jumping abilites'
  - '&b&lhere for cash prizes!'
donor:
  location: spawn, 14.535, 84.200, -1212.006
  lines:
  - '&lDonor Ranks'
  - '&4&lComing Soon!'
crate:
  location: world_nether, 208.553, 134.075, 3.503
  lines:
  - '&uMystery Crate'
  - for testing
suggestions1:
  location: spawn, -6.585, 84.000, -1241.579
  lines:
  - '&uSuggestions'
suggestions2:
  location: spawn, -6.521, 84.000, -1233.448
  lines:
  - '&uSuggestions'
