moon:
  location: spawn, 34.700, 84.000, -1237.487
  lines:
  - '&l&nThe Moon'
  - '&4&lPVP &5&l& &4&lGreifing allowed'
loveyou:
  location: spawn, 14.505, 94.000, -1237.484
  lines:
  - '&4<3'
suggestions1:
  location: hub, -55.340, 71.481, 0.484
  lines:
  - '&u&lSuggestions'
  - '&oBug reports and'
  - '&oserver ideas go here.'
mine:
  location: spawn, 31.513, 84.000, -1220.420
  lines:
  - '&u&lStarter Mine'
crate1:
  location: spawn, -5.878, 85.000, -1244.850
  lines:
  - '&u&lRewards Chest'
  - Opens with Vote & Badass keys
  - '&b&l/Vote &rfor prizes!'
petshop:
  location: spawn, 247.498, 112.739, -1214.514
  lines:
  - '&b&lPet Shop'
junkyard:
  location: spawn, 248.124, 109.386, -1273.504
  lines:
  - '&2&lJunk Yard'
blackmarket:
  location: spawn, 209.509, 101.491, -1377.588
  lines:
  - '&0&lBlack Market'
orchard:
  location: spawn, 83.654, 103.123, -1306.536
  lines:
  - '&c&lOrchard'
farmtown:
  location: spawn, 88.315, 111.815, -1353.303
  lines:
  - '&e&lFarmtown'
library:
  location: spawn, 76.444, 94.700, -1184.800
  lines:
  - '&e&lLibrary'
claymine:
  location: spawn, 79.300, 114.999, -1409.300
  lines:
  - '&u&lClay Mine'
welcome:
  location: spawn, -29.543, 81.089, -1237.472
  lines:
  - '&lWelcome to Prison!'
  - Type &9/warp A &rto start mining
  - Use &9/kits &rto get some gear
  - Walk forward for the tutorial
zombiefarm:
  location: spawn, -141.516, 98.200, -1169.782
  lines:
  - '&4&lZombie Farm'
xpfarm:
  location: spawn, -186.332, 98.287, -1275.533
  lines:
  - '&uExperience Farm'
a_mine:
  location: spawn, 14.502, 93.200, -1313.010
  lines:
  - '&u&lA Mine'
  - '&oSell with &9/sell all'
  - '&oRankup with &9/rankup'
creative:
  location: spawn, 30.472, 85.200, -1255.698
  lines:
  - '&u&lCreative'
survival:
  location: spawn, 34.465, 85.200, -1255.700
  lines:
  - '&u&lSurvival'
plots:
  location: spawn, 26.474, 85.200, -1255.700
  lines:
  - '&u&lPrison Plots'
grief:
  location: world, 131.532, 75.000, 199.655
  lines:
  - '&lGrief Prevention'
  - Play longer, build and explore
  - to claim even more land.
shop:
  location: world, 131.473, 75.200, 229.413
  lines:
  - '&lSurvival Supplies'
welcome2:
  location: world, 125.485, 76.200, 214.554
  lines:
  - '&lWelcome to &9&l/survival'
  - type &9/kits survival &rfor supplies
plotsinfo:
  location: plotworld, 0.513, 71.200, 8.524
  lines:
  - '&u-------------------------------'
  - '&lWelcome to Prison Plots!'
  - '&9/plot claim &rto claim your own'
  - '&9/plot v <ign> &rto visit someones plot'
  - '&9/plot h &rto return to your plot'
  - '&u-------------------------------'
