bounceback: true
worlds:
  world:
    portalgoesto:
      NETHER: hell
      END: world_the_end
  hell:
    portalgoesto:
      NETHER: world
  world_the_end:
    portalgoesto:
      END: world
  world_creative:
    portalgoesto:
      NETHER: hell
