settings:
  mcmmo-leveling: false
  qwick-tree-chopping: false
  apple-chance: 5
  allow-shears: false
messages:
  block:
    saplingdestroy: Let them grow!
    blockplace: This is a treefarm. You can't build here.
    blockdestroy: This is a treefarm. You can't destroy this here.
