# ==== Parkour Config ==== #
Block:
  Finish:
    ID: 43
  Climb:
    ID: 45
    Strength: 0.4
    Type: 1
  Launch:
    ID: 165
    Strength: 1.2
  Bounce:
    ID: 48
    Strength: 0.6
  Run:
    ID: 49
    Strength: 5
    Duration: 200
  Repulse:
    ID: 121
    Strength: 0.4
  NoRun:
    ID: 41
  NoPotion:
    ID: 100
  Death:
    ID:
    - 169
Prize:
  Use: true
  DefaultID: 264
  DefaultAmount: 1
  DefaultXP: 0
SuicideID: 262
CheckpointID: 280
PlatePointID: 1
HideAllID: 352
LeaveID: 6
Other:
  Log: true
  Debug: false
  CheckForUpdates: true
  MaxFall: 100
  LeaderboardType: 1
  Use:
    Economy: true
    BarAPI: false
    ConfirmCJ: false
    ForceFullCompletion: true
    PlatePoints: true
    Prefix: false
    ParkourBlocks: true
    SignProtection: true
    InvManagement: true
    Scoreboard: false
    PlayerDamage: true
    Sounds: true
    Metrics: true
    ForceWorld: false
    OldStatsSigns: false
    SetLevelAsXPBar: false
    CmdPermission: false
    LessCPU: false
  onJoin:
    forceNoFly: true
    forceFinished: false
    GiveSuicideID: true
    GiveHideAllID: true
    GiveLeaveID: true
    GiveStatBook: true
  onLeave:
    ResetPlayer: false
  onDie:
    ResetTimeOnStart: false
    SetAsXPBar: false
  onFinish:
    beCreative: false
    tptoLobby: true
    broadcastInfo: false
  DisableCommands:
    OnParkour: false
  Display:
    WelcomeMessage: false
    CreatorJoin: true
    FinishedError: true
    XPReward: false
    LevelReward: true
  Commands:
    Whitelist: []
Database:
  Use: false
  Host: Host
  User: Username
  Password: Password
  Db: Database
  Table: Table
=== Do NOT Edit anything below here ===: ''
Version: 3.2
Lobby:
  Set: true
  World: parkour
  X: 0.5
  Y: 80.0
  Z: 0.5
  Yaw: 91.45459
  Pitch: 2.5966384
