minBounty: 50.0
listLength: 5
cancelPenalty: 0.25
awardHeadChance: 1.0
markSkulls: true
globalBroadcast: true
allowAnonymous: true
anonymousName: anonymous
enableInAllWorlds: true
enabledWorlds:
- list worlds here if 'enableInAllWorlds' is false
colors:
  failure: §c
  blank: §7
  global: §6
  success: §a
active:
  46654b3a-ef0f-4cea-ac0f-7e94ebef117a:
    97b122ad-aaef-4e44-bb5f-b5c8e9c2fac0:
      reward: 1.0E8
      anonymous: false
    3ec20941-3b49-4346-a72c-f6029968a15a:
      reward: 1.0E8
      anonymous: false
  0815d936-c500-4314-8cb1-605aa6d1ed6b:
    97b122ad-aaef-4e44-bb5f-b5c8e9c2fac0:
      reward: 246.0
      anonymous: false
    46654b3a-ef0f-4cea-ac0f-7e94ebef117a:
      reward: 84.0
      anonymous: false
    e6205cfe-7b5d-4fcb-bd11-801ba6161e0c:
      reward: 234.0
      anonymous: false
    8e1a009a-d3d4-476c-b2ab-43fe1291667f:
      reward: 100.0
      anonymous: false
  97b122ad-aaef-4e44-bb5f-b5c8e9c2fac0:
    2576b041-2329-4256-90ba-e4650989c489:
      reward: 100.0
      anonymous: false
    5d3ee085-5fbc-324a-bb6e-49ef56e5786a:
      reward: 100.0
      anonymous: false
  8e1a009a-d3d4-476c-b2ab-43fe1291667f:
    4486518b-48a2-446b-a0e3-1e2d34dbba15:
      reward: 1010.0
      anonymous: false
    a06acd8a-925f-497f-8998-eb5fbe691d3f:
      reward: 50.0
      anonymous: false
completed: {}
