#  GAListener v1.3.1
#  http://www.minecraft-index.com

#  settings section

#  onlineonly - Only delivers rewards when the player is online.  If they are offline it will wait and deliver when they next join the server!
#  luckyvote - Enables the lucky voting section, this allows voters to have a random chance to receive additional rewards when they vote.
#  permvote - Enables the permission voting section, this allows voters to receive different rewards based upon their permissions.
#  cumulative - Enables the cumulative voting section, this allows voters to receive rewards once they have reached a certain number of votes.
#  broadcastqueue - Show broadcast message for queued votes.
#  broadcastoffline - Show broadcast message for offline queued votes.
#  broadcastrecent - Show broadcast message to recent voters (last 24 hours)
#  votecommand - Enables the /vote command which will show the message contained in the votemessage section at the bottom of the config.
#  rewardcommand - Enables the /rewards command which will show a list of all the cumulative voting rewards.
#  joinmessage - Show the message contained in the joinmessage section at the bottom of this config when a player joins the server.
#  voteremind - Message players who haven't voted in the last 24 hours. Shows the message contained in the remindmessage section at the bottom of this config.
#  remindseconds - How often (in seconds) between each reminder message.
#  ratelimit - Ignore votes received within this many seconds since the last vote for the same player on the same site.  This should prevent duplicate votes.
#  logfile - Log received votes to vote.log file.
#  dbMode - Database mode. Use either mysql or sqlite.
#  dbFile - Database filename for SQLite.
#  dbHost - Database IP / Hostname for MySQL.
#  dbPort - Database port for MySQL.
#  dbUser - Database username for MySQL.
#  dbPass - Database password for MySQL.
#  dbName - Database name for MySQL.
#  dbPrefix - Database table prefix.

settings:
  onlineonly: true
  luckyvote: true
  permvote: false
  cumulative: false
  broadcastqueue: true
  broadcastrecent: true
  broadcastoffline: false
  votecommand: true
  rewardcommand: false
  joinmessage: false
  voteremind: false
  remindseconds: 600
  ratelimit: 10
  logfile: false
  dbMode: 'sqlite'
  dbFile: 'GAL.db'
  dbHost: 'localhost'
  dbPort: 3306
  dbUser: 'root'
  dbPass: ''
  dbName: 'GAL'
  dbPrefix: ''

#  services section (default is used if service doesn't exist)
#  The example below would give 5 diamonds per vote.

#  services section (default is used if service doesn't exist)
services:
  default:
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and recieved a vote key'
    commands:
   - '/crate givekey {username} vote 1'

#  luckyvotes section
luckyvotes:
  '15':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} voted @{GOLD}{service}{GREEN} and luckily won a {AQUA}Badass Key{GREEN}!'
    commands:
    - '/crate givekey {username} badass 1'

#  permission reward section
#  This example would give players with the permission node "gal.double" 10 Diamonds instead of their regular reward.

perms:
  double:
    broadcast: '{GREEN}{username} {GOLD}has voted @ {GREEN}{service} {GOLD}and received {GREEN}10 Diamonds!'
    playermessage: '{GREEN}Thanks for voting at {AQUA}{service}!'
    commands: 
    - '/give {username} 264 10'

#  cumulative reward section

cumulative:
  '10':
    broadcast: '{GREEN}{username} {GOLD}has voted a total of {YELLOW}10 times {GOLD}and received a{GREEN} badass key!'
    playermessage: '{GREEN}Thanks for voting {AQUA}10 times!'
    commands: 
    - '/crate givekey {username} badass 1'

#  blocked - a list of worlds where rewards should be disabled, they will remain queued until the player is in an allowed world.

blocked:
- world_creative
- world
- hell
- parkour

#  Available formatting codes for messages:

#  {service} {servicename} {SERVICE} = service name
#  {username} {player} {name} = player username
#  {votes} = current vote total
#  & = Colour Symbol to enter manual colours / control codes
#  {AQUA} {BLACK} {BLUE} {DARK_AQUA} {DARK_BLUE}
#  {DARK_GRAY} {DARK_GREEN} {DARK_PURPLE} {DARK_RED} {GOLD}
#  {GRAY} {GREEN} {LIGHT_PURPLE} {RED} {WHITE} {YELLOW} {BOLD}
#  {ITALIC} {UNDERLINE} {STRIKETHROUGH} {STRIKE} 
#  {STRIKETHROUGH} {MAGIC} {RESET}

votemessage:
- '{GOLD}-----------------------------------------------------'
- ' ▬▬ι═══- {GREEN} Vote for us on these sites daily for wicked prizes!'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/1m34Vb {GOLD}planetminecraft.com'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/cTHGQu {GOLD}minecraft-server-list.com'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/MmveF1 {GOLD}mineservers.com'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/pXvqaG {GOLD}minecraftservers.org'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/5rVkWx {GOLD}topg.org'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/wAFNrN {GOLD}theminelist.com'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/U5lHIg {GOLD}mcservertrack.com'
- ' ▬▬ι═══- {GREEN} You currently have {AQUA}{votes}{GREEN} total votes'
- '{GOLD}-----------------------------------------------------'

remindmessage:
- '{GOLD}-----------------------------------------------------'
- '{DARK_RED}You have not voted recently, please {BLUE}/vote{DARK_RED} to support the server'
- '{GOLD}-----------------------------------------------------'

joinmessage:
- ' ▬▬ι═══-     {GREEN}Type {BLUE}/vote{GREEN} for links to win daily prizes!'
- '{GOLD}-----------------------------------------------------'

#  Additional formatting codes for below:

#  {TOTAL} = vote total - used for /rewards
#  {REWARD} = current rewardmessage as specified in the cumulative reward section - used for /rewards
#  {POSITION} = current rank - used for /votetop
#  {username} = player name - used for /votetop

rewardformat: '{GREEN}{TOTAL} Votes {GRAY}- {AQUA}{REWARD}'
votetopformat: '{POSITION}. {GREEN}{username} - {WHITE}{TOTAL}'
rewardheader: 
- '{GOLD}---------------- {WHITE}[ {DARK_AQUA}Rewards{WHITE} ] {GOLD}----------------'
votetopheader: 
- '{GOLD}---------------- {WHITE}[ {DARK_AQUA}Top Voters{WHITE} ] {GOLD}----------------'
rewardfooter: 
- '{AQUA}You currently have {GREEN}{votes} Votes'
