#  GAListener v1.3.1
#  http://www.minecraft-index.com

#  settings section

#  onlineonly - Only delivers rewards when the player is online.  If they are offline it will wait and deliver when they next join the server!
#  luckyvote - Enables the lucky voting section, this allows voters to have a random chance to receive additional rewards when they vote.
#  permvote - Enables the permission voting section, this allows voters to receive different rewards based upon their permissions.
#  cumulative - Enables the cumulative voting section, this allows voters to receive rewards once they have reached a certain number of votes.
#  broadcastqueue - Show broadcast message for queued votes.
#  broadcastoffline - Show broadcast message for offline queued votes.
#  broadcastrecent - Show broadcast message to recent voters (last 24 hours)
#  votecommand - Enables the /vote command which will show the message contained in the votemessage section at the bottom of the config.
#  rewardcommand - Enables the /rewards command which will show a list of all the cumulative voting rewards.
#  joinmessage - Show the message contained in the joinmessage section at the bottom of this config when a player joins the server.
#  voteremind - Message players who haven't voted in the last 24 hours. Shows the message contained in the remindmessage section at the bottom of this config.
#  remindseconds - How often (in seconds) between each reminder message.
#  ratelimit - Ignore votes received within this many seconds since the last vote for the same player on the same site.  This should prevent duplicate votes.
#  logfile - Log received votes to vote.log file.
#  dbMode - Database mode. Use either mysql or sqlite.
#  dbFile - Database filename for SQLite.
#  dbHost - Database IP / Hostname for MySQL.
#  dbPort - Database port for MySQL.
#  dbUser - Database username for MySQL.
#  dbPass - Database password for MySQL.
#  dbName - Database name for MySQL.
#  dbPrefix - Database table prefix.

settings:
  onlineonly: true
  luckyvote: true
  permvote: false
  cumulative: false
  broadcastqueue: true
  broadcastrecent: true
  broadcastoffline: false
  votecommand: true
  rewardcommand: false
  joinmessage: false
  voteremind: false
  remindseconds: 600
  ratelimit: 10
  logfile: false
  dbMode: 'sqlite'
  dbFile: 'GAL.db'
  dbHost: 'localhost'
  dbPort: 3306
  dbUser: 'root'
  dbPass: ''
  dbName: 'GAL'
  dbPrefix: ''

#  services section (default is used if service doesn't exist)
#  The example below would give 5 diamonds per vote.

#  services section (default is used if service doesn't exist)
services:
  default:
    #broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and'

#  luckyvotes section
luckyvotes:
  '250':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Dragon Egg!'
    commands:
    - '/give {username} 122 1'
  '150':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won an assload of stinky{AQUA} Raw Salmon because Fuck You!'
    commands:
    - '/give {username} 349:1 256'
  '150':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won an {AQUA} Entire Library!'
    commands:
    - '/give {username} 47 128'
  '100':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a pair of{AQUA} Air Jordans'
    commands:
    - '/give {username} 313 1 0 {display:{Name:"Air Jordans"},ench:[{id:2,lvl:1000},{id:0,lvl:5}]}'
  '100':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Scuba Mask'
    commands:
    - '/give {username} 310 1 0 {display:{Name:"Scuba Mask"},ench:[{id:5,lvl:1000},{id:0,lvl:5}]}'
  '100':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Nether Star!'
    commands:
    - '/give {username} 399 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Creeper Fetus!'
    commands:
    - '/give {username} 383:50 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Skeleton Fetus!'
    commands:
    - '/give {username} 383:51 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Spider Fetus!'
    commands:
    - '/give {username} 383:52 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Zombie Fetus!'
    commands:
    - '/give {username} 383:54 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Slime Fetus!'
    commands:
    - '/give {username} 383:55 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Ghast Fetus!'
    commands:
    - '/give {username} 383:56 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Pigman Fetus!'
    commands:
    - '/give {username} 383:57 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Enderman Fetus!'
    commands:
    - '/give {username} 383:58 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Cave Spider Fetus!'
    commands:
    - '/give {username} 383:59 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Magma Cube Fetus!'
    commands:
    - '/give {username} 383:61 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Bat Fetus!'
    commands:
    - '/give {username} 383:65 1'
  '85':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Witch Fetus!'
    commands:
    - '/give {username} 383:66 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Pig Fetus!'
    commands:
    - '/give {username} 383:90 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Sheep Fetus!'
    commands:
    - '/give {username} 383:91 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Cow Fetus!'
    commands:
    - '/give {username} 383:92 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Chicken Fetus!'
    commands:
    - '/give {username} 383:93 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Squid Fetus!'
    commands:
    - '/give {username} 383:94 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Wolf Fetus!'
    commands:
    - '/give {username} 383:95 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} MooShroom Fetus!'
    commands:
    - '/give {username} 383:96 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Feline Fetus!'
    commands:
    - '/give {username} 383:98 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Horse Fetus!'
    commands:
    - '/give {username} 383:100 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Villager Fetus!'
    commands:
    - '/give {username} 383:120 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won an{AQUA} Enchanting Table!'
    commands:
    - '/give {username} 116 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Brewing Stand!'
    commands:
    - '/give {username} 117 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won an{AQUA} Ender Chest!'
    commands:
    - '/give {username} 130 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won an{AQUA} Anvil!'
    commands:
    - '/give {username} 145 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a beautiful{AQUA} Painting!'
    commands:
    - '/give {username} 321 1'
  '75':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Clock!'
    commands:
    - '/give {username} 347 1'
  '70':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won{AQUA} $25000!'
    commands:
    - '/money give {username} 25000'
  '63':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Cake!'
    commands:
    - '/give {username} 92 1'
  '63':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Bed!'
    commands:
    - '/give {username} 355 1'
  '62':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won some{AQUA} Warts!'
    commands:
    - '/give {username} 372 5'
  '61':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Light Sensor!'
    commands:
    - '/give {username} 151 1'
  '50':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a{AQUA} Beacon!'
    commands:
    - '/give {username} 138 1'
  '50':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won{AQUA} $10000!'
    commands:
    - '/money give {username} 10000'
  '45':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won a bucket of{AQUA} Milk from Rihannas Tits!'
    commands:
    - '/give {username} 335 1'
  '40':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won{AQUA} 32 XP Bottles!'
    commands:
    - '/give {username} 384 32'
  '15':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won{AQUA} $5000!'
    commands:
    - '/money give {username} 5000'
  '10':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} has voted @{GOLD}{service}{GREEN} and won{AQUA} $500!'
    commands:
    - '/money give {username} 500'
  '1':
    broadcast: '{BLUE}[{GREEN}RD-Prison{BLUE}]{AQUA} {username}{GREEN} voted @{GOLD}{service}{GREEN} and has earned a {AQUA}Voting Key{GREEN}!'
    commands:
    - '/crate givekey {username} vote 1'

#  permission reward section
#  This example would give players with the permission node "gal.double" 10 Diamonds instead of their regular reward.

perms:
  double:
    broadcast: '{GREEN}{username} {GOLD}has voted @ {GREEN}{service} {GOLD}and received {GREEN}10 Diamonds!'
    playermessage: '{GREEN}Thanks for voting at {AQUA}{service}!'
    commands: 
    - '/give {username} 264 10'

#  cumulative reward section

cumulative:
  '10':
    broadcast: '{GREEN}{username} {GOLD}has voted a total of {YELLOW}10 times {GOLD}and received {GREEN}$10,000!'
    playermessage: '{GREEN}Thanks for voting {AQUA}10 times!'
    commands: 
    - '/money give {username} 10000'
  '20':
    broadcast: '{GREEN}{username} {GOLD}has voted a total of {YELLOW}20 times {GOLD}and received {GREEN}$50,000!'
    playermessage: '{GREEN}Thanks for voting {AQUA}20 times!'
    commands:
    - '/money give {username} 50000'
  '30':
    broadcast: '{GREEN}{username} {GOLD}has voted a total of {YELLOW}20 times {GOLD}and received {GREEN}$100,000!'
    playermessage: '{GREEN}Thanks for voting {AQUA}30 times!'
    commands:
    - '/money give {username} 100000'

#  blocked - a list of worlds where rewards should be disabled, they will remain queued until the player is in an allowed world.

blocked:
- world_blocked

#  Available formatting codes for messages:

#  {service} {servicename} {SERVICE} = service name
#  {username} {player} {name} = player username
#  {votes} = current vote total
#  & = Colour Symbol to enter manual colours / control codes
#  {AQUA} {BLACK} {BLUE} {DARK_AQUA} {DARK_BLUE}
#  {DARK_GRAY} {DARK_GREEN} {DARK_PURPLE} {DARK_RED} {GOLD}
#  {GRAY} {GREEN} {LIGHT_PURPLE} {RED} {WHITE} {YELLOW} {BOLD}
#  {ITALIC} {UNDERLINE} {STRIKETHROUGH} {STRIKE} 
#  {STRIKETHROUGH} {MAGIC} {RESET}

votemessage:
- '{GOLD}-----------------------------------------------------'
- ' ▬▬ι═══- {GREEN} Vote for us on these sites daily for wicked prizes!'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/1m34Vb {GOLD}planetminecraft.com'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/cTHGQu {GOLD}minecraft-server-list.com'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/MmveF1 {GOLD}mineservers.com'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/pXvqaG {GOLD}minecraftservers.org'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/5rVkWx {GOLD}topg.org'
- ' ▬▬ι═══- {GREEN} {BLUE}http://goo.gl/wAFNrN {GOLD}theminelist.com'
- ' ▬▬ι═══- {GREEN} You currently have {AQUA}{votes}{GREEN} total votes'
- '{GOLD}-----------------------------------------------------'

remindmessage:
- '{GOLD}-----------------------------------------------------'
- '{DARK_RED}You have not voted recently, please {BLUE}/vote{DARK_RED} to support the server'
- '{GOLD}-----------------------------------------------------'

joinmessage:
- ' ▬▬ι═══-     {GREEN}Type {BLUE}/vote{GREEN} for links to win daily prizes!'
- '{GOLD}-----------------------------------------------------'

#  Additional formatting codes for below:

#  {TOTAL} = vote total - used for /rewards
#  {REWARD} = current rewardmessage as specified in the cumulative reward section - used for /rewards
#  {POSITION} = current rank - used for /votetop
#  {username} = player name - used for /votetop

rewardformat: '{GREEN}{TOTAL} Votes {GRAY}- {AQUA}{REWARD}'
votetopformat: '{POSITION}. {GREEN}{username} - {WHITE}{TOTAL}'
rewardheader: 
- '{GOLD}---------------- {WHITE}[ {DARK_AQUA}Rewards{WHITE} ] {GOLD}----------------'
votetopheader: 
- '{GOLD}---------------- {WHITE}[ {DARK_AQUA}Top Voters{WHITE} ] {GOLD}----------------'
rewardfooter: 
- '{AQUA}You currently have {GREEN}{votes} Votes'
