# Language, supported en, hu ( send me translations! )
Locale: en
Check-update: true
Farming:
  Disable-spawner-farming: false
  Disable-egg-farming: true
Hook:
  MobArena:
    Enabled: false
    Config-processing-when-players-in-arena: false
Decimal-places: 2
Global-settings:
  Money-multiplier: 1
  Disable-functions-on-these-worlds:
  - world_the_end
  Disable-functions-in-creative-mode: true
