#Prefix of the Message
MessagePrefix: "&9[&aRD-Prison&9]"

# %currency value (e.g. Dollar, Forint, Euro or symbol)
Currency: "$"

#If you reloaded the config, you will get this message
MessageConfigReload: "The configuration file reloaded"

# Command permission
MessageNoPermission: "You have not permission for this command!"

# Player message, if  the config is bad
MessageConfigError: "Config Error! Please report to admin!"

# Set True, if you want give money if the player kill mobs in the MobArena
EarnMoneyInMobArena: true

# Multiworld support, you can disable this plugin on some worlds. Use "," if you would like add more worlds. ( E.g.: world_nether,world_the_end )
# Use "nothing" if you wouldn't like this feature.
DisableOnThisWorlds: nothing

# This option disable that the player get cash, if the mob spawned from spawner or spawner egg.
DisableSpawnerFarming: false

# You can enable or disable that, the players get message if he/she earn money.
SendMessageWhenEarnMoney: true

# 1st line: The mob's name, do not change it!
# 2nd line (Enabled): If you want give money for this mob kill
# 3rd line (Negative): If you want negative cash (withdraw) then set true
# 4th line (MinMoney): The minimum money for kill
# 5th line (MaxMoney): The maximum money for kill
# 6th line (Message): The player get this message, if he/she killed a mob
# 7th line (MessageNegative): If you set Negative to true, then this message will be send to player

# String List:
# %currency = Currency value
# %money = Earned money
# %playername = Killer player's name
# %victim = Killed player's name

# If you would like give fix money, then must MinMoney equal with MaxMoney!

Pig:
   Enabled: true
   Negative: false
   MinMoney: 20
   MaxMoney: 50
   Message: "&7You killed a &6Pig&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Sheep:
   Enabled: true
   Negative: false
   MinMoney: 20
   MaxMoney: 50
   Message: "&7You killed a &6Sheep&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Chicken:
   Enabled: true
   Negative: false
   MinMoney: 20
   MaxMoney: 50
   Message: "&7You killed a &6Chicken&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Cow:
   Enabled: true
   Negative: false
   MinMoney: 20
   MaxMoney: 50
   Message: "&7You killed a &6Cow&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"

Horse:
   Enabled: true
   Negative: true
   MinMoney: 1000
   MaxMoney: 10000
   Message: "&7You killed a &6Horse&7! You earned: &6%currency%money"
   MessageNegative: "&6Asshole! &7You lost &6%currency%money &7for killing a Horse!"
   
Wolf:
   Enabled: true
   Negative: true
   MinMoney: 1000
   MaxMoney: 10000
   Message: "&7You killed a &6Wolf&7! You earned: &6%currency%money"
   MessageNegative: "&6Asshole! &7You lost &6%currency%money &7for killing a Puppy!"
   
Ocelot:
   Enabled: true
   Negative: true
   MinMoney: 1000
   MaxMoney: 10000
   Message: "&7You killed an &6Kitten&7! You earned: &6%currency%money"
   MessageNegative: "&6Asshole! &7You lost &6%currency%money &7for killing a Kitten!"
   
Bat:
   Enabled: true
   Negative: false
   MinMoney: 5
   MaxMoney: 100
   Message: "&7You killed a &6Bat&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Blaze:
   Enabled: true
   Negative: false
   MinMoney: 50
   MaxMoney: 175
   Message: "&7You killed a &6Blaze&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
CaveSpider:
   Enabled: true
   Negative: false
   MinMoney: 25
   MaxMoney: 100
   Message: "&7You killed a &6Cave Spider&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Creeper:
   Enabled: true
   Negative: false
   MinMoney: 25
   MaxMoney: 100
   Message: "&7You killed a &6Creeper&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Enderdragon:
   Enabled: true
   Negative: false
   MinMoney: 1000
   MaxMoney: 10000
   Message: "&7You killed the &6Ender Dragon&7! You earned: &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Enderman:
   Enabled: true
   Negative: false
   MinMoney: 35
   MaxMoney: 35
   Message: "&7You killed an &6Enderman&7! You earned: &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Ghast:
   Enabled: true
   Negative: false
   MinMoney: 35
   MaxMoney: 35
   Message: "&7You killed a &6Ghast&7! You earned: &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Giant:
   Enabled: true
   Negative: false
   MinMoney: 35
   MaxMoney: 300
   Message: "&7You killed a &6Giant&7! You earned: &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
MagmaCube:
   Enabled: true
   Negative: false
   MinMoney: 25
   MaxMoney: 200
   Message: "&7You killed a &6Magma Cube&7! You earned: &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
MushroomCow:
   Enabled: true
   Negative: false
   MinMoney: 5
   MaxMoney: 100
   Message: "&7You killed a &6Mushroom Cow&7! You earned: &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
PigZombie:
   Enabled: true
   Negative: false
   MinMoney: 35
   MaxMoney: 150
   Message: "&7You killed a &6Pig Zombie&7! You earned: &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Player:
   Enabled: true
   Negative: false
   MinMoney: 0
   MaxMoney: 0
   # The killer take percent of victim money ( 0 disabled, max 100, default 10 )
   CashTransmissionPercent: 5
   Message: "&6Woot! &7You killed &6%victim&6! &7You picked up: &6%currency%money"
   MessageNegative: "&6Fail! &7%playername&6, &7you lost &6%currency%money"
   MessageToVictimIfLostCash: "&7Fail&6! &7You lost &6%currency%lostmoney&7, because youve been owned by &6%playername&7!"
   
Silverfish:
   Enabled: true
   Negative: false
   MinMoney: 15
   MaxMoney: 30
   Message: "&7You killed a &6Silverfish&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Skeleton:
   Enabled: true
   Negative: false
   MinMoney: 25
   MaxMoney: 100
   Message: "&7You killed a &6Skeleton&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Slime:
   Enabled: true
   Negative: false
   MinMoney: 25
   MaxMoney: 75
   Message: "&7You killed a &6Pig&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Spider:
   Enabled: true
   Negative: false
   MinMoney: 25
   MaxMoney: 75
   Message: "&7You killed a &6Spider&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Squid:
   Enabled: true
   Negative: false
   MinMoney: 10
   MaxMoney: 10
   Message: "&7You killed a &6Squid&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Villager:
   Enabled: true
   Negative: true
   MinMoney: 10000
   MaxMoney: 10000
   Message: "&7You killed a &6Villager&7 and earned &6%currency%money"
   MessageNegative: "&4Murderer! &7%playername&6, &7you killed a villager and have been fined &6%currency%money"
   
Witch:
   Enabled: true
   Negative: false
   MinMoney: 35
   MaxMoney: 35
   Message: "&7You killed a &6Witch&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Wither:
   Enabled: true
   Negative: false
   MinMoney: 10000
   MaxMoney: 10000
   Message: "&7You killed a &6Wither&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
   
Zombie:
   Enabled: true
   Negative: false
   MinMoney: 50
   MaxMoney: 150
   Message: "&7You killed a &6Zombie&7 and earned &6%currency%money"
   MessageNegative: "&6Ops! &7%playername&6, &7you lost &6%currency%money"
