# 
# VanishNoPacket
#   A fine choice of invisibility for the discerning server administrator.
#   http://www.kitteh.org
fakeannounce:
  automaticforsilentjoin: true
  join: '&&b&&l&&l>>&&e&&l&&oLog&&a+&&e&&l&&oin&&b&&l&&o>> &&r%p'
  quit: '&&d&&l&&l>>&&c&&l&&oLogout&&d&&l&&o>> &&r%p'
hooks:
  essentials: true
  dynmap: false
  JSONAPI: false
  spoutcraft: false
checkupdates: true
permissionsupdates:
  checkonworldchange: false
effects:
  lightning:
    count: 4
colornametags: true
permtest: false
debug: false
configVersionDoNotTouch:
  SeriouslyThisWillEraseYourConfig: 5
