mine:
  ==: pMine
  region:
    ==: PrisonRegion
    minimum:
      ==: Vector
      x: -80.0
      y: 83.0
      z: -1368.0
    maximum:
      ==: Vector
      x: -72.0
      y: 108.0
      z: -1360.0
    world: spawn
  flags: []
  breakBlacklist:
    ==: Blacklist
    blocks: {}
    type: 0
  parent: null
  blocks:
  - ==: MineBlock
    blockData: 0
    blockId: 0
    chance: 0.0
  - ==: MineBlock
    blockData: 0
    blockId: 57
    chance: 1.0
  tpPoint:
    ==: SimpleLoc
    yaw: 180.87732
    pitch: 2.2499151
    z: -1355.7479297626526
    y: 108.0
    world: spawn
    x: -75.58982894682018
  blocksLeft: 2106
  resetTriggers:
  - ==: CompositionTrigger
    percent: '0.4'
    mine: ProDonor
  id: ProDonor
  warningTimes: []
  placeBlacklist:
    ==: Blacklist
    blocks: {}
    type: 0
  cooldownPeriod: 0
  name: ''
  blockReplaceBlacklist:
    ==: Blacklist
    blocks: {}
    type: 0
  protectionRegion:
    ==: PrisonRegion
    minimum:
      ==: Vector
      x: -80.0
      y: 83.0
      z: -1368.0
    maximum:
      ==: Vector
      x: -72.0
      y: 108.0
      z: -1360.0
    world: spawn
  world: spawn
  enabledProtection: []
  cooldownEnabled: false
