# dynmap-plotme configuration
update:
  period: 300
  onchange: true
layer:
  name: PlotMe
  hidebydefault: false
  layerprio: 1
  minzoom: 0
resdepth: 2
infowindow: '<div class="infowindow"><span style="font-size:120%;">ID : %plotid%</span><br
  /> Owner <span style="font-weight:bold;">%plotowners%</span>%plothelpers%'
plotstyle:
  strokeColor: '#FF0000'
  strokeOpacity: 0.5
  strokeWeight: 8
  fillColor: '#FFFFFF'
  fillOpacity: 0.01
visibleregions: []
hiddenregions: []
custstyle:
  customizedplot:
    strokeColor: '#00FF00'
    y: 64
  anotherregion:
    subzone:
      strokeColor: '#007F00'
