Messages:
  timeleftofcombat: You have %time% seconds left of Combat!
  notincombat: You're not in Combat.
  nowincombat: You're in Combat, type '/ct' to check your remaining tag time.
  outofcombat: You're now out of Combat!
  canttpincombat: You can't teleport in Combat!
  oncombatlog: '%player% logged out in Combat!'
  canttypecommand: '&4You can''t type that command in Combat.'
canTPincombat: false
disableCreative: true
disableFly: true
combattime: 10
disableDisguise: true
blocked-cmds:
- spawn
- warp
disabledWorlds:
- disabledWorld1
