cfg-version: 11
message: '&cYou have reached the edge of this world.'
round-border: true
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: The border of the world.
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids:
- 46654b3a-ef0f-4cea-ac0f-7e94ebef117a
- 03c43156-b8be-409c-b0d2-a666499147c5
- 7d345a63-2052-4623-bef8-4245fbc9b321
- 17d5c2c2-163b-43d7-b691-0dc3ede51790
- 70c62c14-ce92-4c40-a48c-c79a166dd666
fill-memory-tolerance: 500
prevent-block-place: false
prevent-mob-spawn: false
worlds:
  hell:
    x: 38.5
    z: -43.5
    radiusX: 500
    radiusZ: 500
    wrapping: false
  world_the_end:
    x: 11.220366866042339
    z: 16.50045295174567
    radiusX: 300
    radiusZ: 300
    wrapping: false
  free:
    x: -299.5
    z: -153.5
    radiusX: 5500
    radiusZ: 5500
    wrapping: false
  plotworld:
    x: 0.5114026927490404
    z: 0.48000159162498857
    radiusX: 200
    radiusZ: 200
    wrapping: false
  world:
    x: 131.50720036660329
    z: 214.4646094475723
    radiusX: 2000
    radiusZ: 2000
    wrapping: false
