cfg-version: 11
message: '&cYou have reached the edge of this world.'
round-border: true
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: The border of the world.
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids:
- 46654b3a-ef0f-4cea-ac0f-7e94ebef117a
- 7d345a63-2052-4623-bef8-4245fbc9b321
- 03c43156-b8be-409c-b0d2-a666499147c5
fill-memory-tolerance: 500
worlds:
  hell:
    x: 38.5
    z: -43.5
    radiusX: 500
    radiusZ: 500
    wrapping: false
  world_the_end:
    x: 11.220366866042339
    z: 16.50045295174567
    radiusX: 300
    radiusZ: 300
    wrapping: false
  free:
    x: -299.5
    z: -153.5
    radiusX: 5500
    radiusZ: 5500
    wrapping: false
  plotworld:
    x: 0.5114026927490404
    z: 0.48000159162498857
    radiusX: 200
    radiusZ: 200
    wrapping: false
  spawn:
    x: 14.5
    z: -1237.5
    radiusX: 300
    radiusZ: 300
    wrapping: false
  world:
    x: 131.4934096204236
    z: 214.4897017985034
    radiusX: 1000
    radiusZ: 1000
    wrapping: false
