cfg-version: 11
message: '&cYou have reached the edge of this world.'
round-border: true
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: The border of the world.
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids:
- 7d345a63-2052-4623-bef8-4245fbc9b321
- 46654b3a-ef0f-4cea-ac0f-7e94ebef117a
fill-memory-tolerance: 500
worlds:
  hell:
    x: 38.5
    z: -43.5
    radiusX: 500
    radiusZ: 500
    wrapping: false
  world_the_end:
    x: 11.220366866042339
    z: 16.50045295174567
    radiusX: 300
    radiusZ: 300
    wrapping: false
  free:
    x: -299.5
    z: -153.5
    radiusX: 5500
    radiusZ: 5500
    wrapping: false
  plotworld:
    x: 10.5
    z: 8.5
    radiusX: 500
    radiusZ: 500
    wrapping: false
