# InventoryFull version 1.5.1
# Created by: extended_clip
# Valid placeholders:
# %block% - display the dropped item type
# %player% - display the players name
cooldown_time: 2
max_alerts_until_cooldown: 1
chat_message:
  use_chat_message: false
  message:
  - '&cYour inventory is full!'
actionannouncer:
  use_actionbar: false
  message: '&cYour inventory is full!'
titlemanager:
  use_title: false
  title: '&cYou don''t have room in your inventory'
  subtitle: to collect that &f%block%&c!
  fade_in: 12
  fade_out: 12
  duration: 20
  use_actionbar: false
  actionbar_message: '&cYou don''t have room in your inventory'
holographicdisplays:
  use_hologram: true
  message:
  - '&cYour inventory'
  - '&cis full!'
  display_time: 2
