Locale: en_US
Action: INK_SACK:0
EditCosts: false
SignColors: true
OnlyInOwnedRegion: false
NotifyUpdates: true
AutoUpdate: true
Copy:
  Item: PAPER
  Ink: INK_SACK:0
  CopyCosts: false
  PasteCosts: false
