prefix:
  prefix: '&9[Dragon Slayer]&r '
  enabled: true
dragon:
  name: '&5Smaug&r'
  damage: 10.0
  health: 200
  exp: 12000
  reward: 2500.0
  eggchance: 0.3
  createportal: false
  blockgrief: false
  slain: false
  respawndelay: 10
  slayer: mickverm
messages:
  respawn: '$dragon &4has risen from its ashes!'
  onkill: '&6$slayer &fkilled &4$dragon &rand became the new &9Dragon Slayer!'
  onrekill: '&9Dragon Slayer &6$slayer &fkilled &4$dragon &ronce again!'
  slayer: '&6$slayer &fis the one and only &9Dragon Slayer!'
  noslayer: 'There currently is no hero who can call himself the true &9Dragon Slayer!'
  reward: 'You received &6$reward coins &rfor killing &4$dragon'
spawnpoint:
  world: 'world_the_end'
  x: 0
  y: 96
  z: 0
