# AutoAnnouncer Settings by Sharkiller #
Settings:
  Interval: 5
  InSeconds: false
  Random: false
  Permission: false
Announcer:
  Tag: '&a&o&l>>&c&o&lRD&e*&b&o&lNEWS&a&o&l>>&r'
  ToGroups: false
  Groups:
  - Default
  Strings:
  - 'Looking for the server map? Click here: &9http://goo.gl/rqPpHw&NEW_LINE;'
  - 'Want to help promote the server? Visit our PMC page here: &9http://goo.gl/snFGCR &rto subscribe, diamond and favorite us.&NEW_LINE;'
  - 'Looking for badass OP gear? &9/vote &rfor reward chest keys and maybe you will win a badass key!&NEW_LINE;'
  - 'Have you found all the hidden warps yet? Theres now 23 total to unlock! &NEW_LINE;'
  - 'Dont forget to checkout the new &9/warp playershops &rfor awesome deals and gear!&NEW_LINE;'
  - 'Make friends by welcoming new players to the server and helping them get started. Thats Special!&NEW_LINE;'
  - 'Want to earn cash quick? Try voting! Theres lots of diamonds and prizes to be won! Type &9/vote &rfor the links.&NEW_LINE;'
  - 'Warning: Plotworld is messy enough! Plots without walls or proper lighting will be reset without notice!&NEW_LINE;'
  - 'Remember to invite your friends to play alongside you, it supports the server and makes things a lot more fun!&NEW_LINE;'
  - 'Still have questions? Visit the prison tutorial by typing &9/warp tutorial&r. Or check the rules by typing &9/rules&r.&NEW_LINE;'
  - 'Bored? Try looking for a few of the many secrets, easter eggs and warps that are hidden all over prison!&NEW_LINE;'
  - 'Need to sell something fancy? Try starting an auction! Type &9/auction &rfor help.&NEW_LINE;'
