# AutoAnnouncer Settings by Sharkiller #
Settings:
  Interval: 5
  InSeconds: false
  Random: false
  Permission: false
Announcer:
  Tag: '&a&o&l>>&c&o&lRD&e*&b&o&lNEWS&a&o&l>>&r'
  ToGroups: false
  Groups:
  - Default
  Strings:
  - 'Bug reports and Suggestions are greatly appreciated! They can be submitted at&9/spawn'
  - 'We have a server map! &9http://goo.gl/rqPpHw'
  - 'Want to help promote the server? Visit &9http://goo.gl/snFGCR &rto subscribe, diamond and favorite us.'
  - 'Looking for badass OP gear? &9/vote &rfor reward chest keys and maybe you will win a badass key!'
  - 'Have you found all the hidden warps yet? Theres now 23 total to unlock!'
  - 'Dont forget to checkout the new &9/warp playershops &rfor awesome deals and gear!'
  - 'Make friends by welcoming new players to the server and helping them get started. Thats Special!'
  - 'Want to earn cash quick? Theres lots of diamonds and prizes to be won! Type &9/vote &rfor the links.'
  - 'Warning: Plotworld is messy enough! Plots without walls or proper lighting will be reset without notice!'
  - 'Invite your friends to play along, it supports the server and makes things a lot more fun!'
  - 'Still have questions? Visit the prison tutorial by typing &9/warp tutorial&r. Or check the rules by typing &9/rules&r.&NEW_LINE;'
  - 'There are many secrets, easter eggs and warps that are hidden all over prison!'
  - 'Try starting an &9/auction&r!'
