########################################
# AutoAnnouncer Settings by Sharkiller #
###############################################################
# To support unicode characters save the file in UTF-8 format #
###############################################################
Settings:
    # Scheduler Interval in minutes
    Interval: 5
    # If interval is in seconds
    InSeconds: false
    # true: random | false: consecutive
    Random: false
    # true: permissions security | false: only OP's
    Permission: false
Announcer:
    # Tag for Announcement. May be empty: ''
    Tag: '&9[&cRD-News&9]&a'
    # true: certain groups in permissions | false: to all
    ToGroups: false
    # Groups to send announcement. Only if ToGroups is true.
    Groups:
        - 'Default'
    # Strings to announce
    # If you have problems check your syntax here:
    # http://yaml-online-parser.appspot.com/
    Strings:
        - "Looking for badass OP gear? &9/vote &afor reward chest keys and maybe you'll win a badass key!"
        - "Have you found all the hidden warps yet? Theres now 17 total to unlock!"
        - "Don't forget to checkout the new &9/warp playershops &afor awesome deals and gear!"
        - "Make friends by welcoming new players to the server and helping them get started. That's Special!"
        - "Want to earn cash quick? Try voting! There's lots of diamonds and prizes to be won! Type &9/vote &afor the links."
        - "Warning: Plotworld is dangerous enough! Plots without walls or proper lighting will be reset without notice!"
        - "Remember to invite your friends to play alongside you, it supports the server and makes things a lot more fun!"
        - "Still have questions? Visit the prison tutorial by typing &9/warp tutorial&a. Or check the rules by typing &9/rules&a."
        - "Bored? Try looking for a few of the many secrets, easter eggs and warps that are hidden all over prison!"
        - "Feeling dangerous? Try the PVP Mine, type &9/warp pvp&a to get there."
        - "Need to sell something fancy? Try starting an auction! Type &9/auction &afor help."
