# 
# AutoAnnouncer Settings by Sharkiller #
Settings:
  Interval: 5
  InSeconds: false
  Random: false
  Permission: false
Announcer:
  Tag: '/n&a&o&l>>&c&o&lRD&e*&b&o&lNEWS&a&o&l>>&r'
  ToGroups: false
  Groups:
  - Default
  Strings:
  - 'Looking for the server map? Click here: &9http://goo.gl/rqPpHw'
  - 'Want to help promote the server? Visit our PMC page here: &9http://goo.gl/snFGCR &rto subscribe, diamond and favorite us.'
  - Looking for badass OP gear? &9/vote &rfor reward chest keys and maybe you'll win a badass key!
  - Have you found all the hidden warps yet? Theres now 23 total to unlock!
  - Don't forget to checkout the new &9/warp playershops &rfor awesome deals and gear!
  - Make friends by welcoming new players to the server and helping them get started. That's Special!
  - Want to earn cash quick? Try voting! There's lots of diamonds and prizes to be won! Type &9/vote &rfor the links.
  - 'Warning: Plotworld is messy enough! Plots without walls or proper lighting
    will be reset without notice!'
  - Remember to invite your friends to play alongside you, it supports the server and makes things a lot more fun!
  - Still have questions? Visit the prison tutorial by typing &9/warp tutorial&r. Or check the rules by typing &9/rules&r.
  - Bored? Try looking for a few of the many secrets, easter eggs and warps that are hidden all over prison!
  - Feeling dangerous? Try the PVP Mine, type &9/warp pvp&r to get there.
  - Need to sell something fancy? Try starting an auction! Type &9/auction &rfor help.
