# AutoAnnouncer Settings by Sharkiller #
Settings:
  Interval: 5
  InSeconds: false
  Random: true
  Permission: false
Announcer:
  Tag: '&a&o&l>>&c&o&lRD&e*&b&o&lNEWS&a&o&l>>&r'
  ToGroups: false
  Groups:
  - Default
  Strings:
  - 'Suggestions are greatly appreciated! The commands are: &9/suggest <message> &ror &9/feedback <message>&r.'
  - 'Use &9/hub &rto return to the spawn portals'
  - 'Want to help promote the server? Visit &9http://goo.gl/snFGCR &rto subscribe, diamond and favorite us.'
  - 'Looking for badass OP gear? &9/vote &rfor reward chest keys and maybe you will win a badass key!'
  - 'Have you found all the hidden prison warps yet? Theres now 24 total to unlock!'
  - 'Make friends by welcoming new players to the server and helping them get started. Thats Special!'
  - 'Want to earn cash quick? Theres lots of diamonds and prizes to be won! Type &9/vote &rfor the links.'
  - 'Warning: Plotworld is messy enough! Plots without walls or proper lighting will be reset without notice!'
  - 'Invite your friends to play along, it supports the server and makes things a lot more fun!'
  - 'Still have questions? Visit the prison tutorial by typing &9/warp tutorial&r. Or check the rules by typing &9/rules&r.'
  - 'There are many secrets, easter eggs and warps that are hidden all over prison!'
  - 'Bored? Try a new gamemode or realm with: &9/survival&r, &9/creative &ror &9/skyblock&r.'
