# Spawner config file
# 
# Valid entities
valid_entities:
- Creeper
- Skeleton
- Spider
- Giant
- Zombie
- Slime
- Ghast
- PigZombie
- Enderman
- CaveSpider
- Silverfish
- Blaze
- LavaSlime
- EnderDragon
- WitherBoss
- Bat
- Witch
- Pig
- Sheep
- Cow
- Chicken
- Squid
- Wolf
- MushroomCow
- SnowMan
- Ozelot
- VillagerGolem
- EntityHorse
- Villager
- FireworksRocketEntity
- Guardian
- Endermite
- Rabbit
aliases:
  WitherBoss:
  - wither
  VillagerGolem:
  - golem
  - irongolem
  EntityHorse:
  - horse
protect_from_explosions: 'true'
remove_radius: 10
luck: 100
frequency:
  Creeper: 100
  Skeleton: 100
  Spider: 100
  Giant: 100
  Zombie: 100
  Slime: 100
  Ghast: 100
  PigZombie: 100
  Enderman: 100
  CaveSpider: 100
  Silverfish: 100
  Blaze: 100
  LavaSlime: 100
  EnderDragon: 100
  WitherBoss: 100
  Bat: 100
  Witch: 100
  Pig: 100
  Sheep: 100
  Cow: 100
  Chicken: 100
  Squid: 100
  Wolf: 100
  MushroomCow: 100
  SnowMan: 100
  Ozelot: 100
  VillagerGolem: 100
  EntityHorse: 100
  Villager: 100
  FireworksRocketEntity: 100
  Guardian: 100
  Endermite: 100
  Rabbit: 100
drops:
  Creeper: []
  Skeleton: []
  Spider: []
  Giant: []
  Zombie: []
  Slime: []
  Ghast: []
  PigZombie: []
  Enderman: []
  CaveSpider: []
  Silverfish: []
  Blaze: []
  LavaSlime: []
  EnderDragon: []
  WitherBoss: []
  Bat: []
  Witch: []
  Pig: []
  Sheep: []
  Cow: []
  Chicken: []
  Squid: []
  Wolf: []
  MushroomCow: []
  SnowMan: []
  Ozelot: []
  VillagerGolem: []
  EntityHorse: []
  Villager: []
  FireworksRocketEntity: []
  Guardian: []
  Endermite: []
  Rabbit: []
