usingConfig: true
config-version: 3
tabmenu:
  enabled: true
  header: '&c&lRock &b&lDiamond'
  footer: '&e&lmc.rockdiamond.net'
welcome_message:
  enabled: true
  title: '&c&lRock &b&lDiamond'
  subtitle: '&5Welcomes you back {PLAYER}!'
  fadeIn: -1
  stay: -1
  fadeOut: -1
  first-join:
    title: '&c&lRock &b&lDiamond'
    subtitle: '&dHope you enjoy your stay!'
number-format:
  enabled: true
  format: '#,###.##'
date-format:
  format: EEE, dd MMM yyyy HH:mm:ss z
using-bungeecord: false
actionbar-welcome:
  enabled: true
  message: '&a&lWelcome!'
  first-join:
    message: '&2&lWelcome It''s your first time!'
disabled-variables:
- my-disabled-variable
- also-called-placeholders
legacy-client-support: false
updater:
  check-automatically: true
