usingConfig: true
config-version: 3
using-bungeecord: false
legacy-client-support: false
updater:
  check-automatically: true
tabmenu:
  enabled: true
  header: ' &9Rock Diamond &bNetwork '
  footer: ' mc.rockdiamond.net '
welcome_message:
  enabled: true
  title: '&7Welcome &a{PLAYER}&7!'
  subtitle: To &9Rock Diamond &bNetwork
  fadeIn: 20
  stay: 40
  fadeOut: 20
  first-join:
    title: '&7Welcome &a{PLAYER}'
    subtitle: To &9Rock Diamond &bNetwork
actionbar-welcome:
  enabled: false
  message: '&a&lWelcome!'
  first-join:
    message: '&2&lWelcome It''s your first time!'
number-format:
  enabled: true
  format: '#,###.##'
date-format:
  format: EEE, dd MMM yyyy HH:mm:ss z
disabled-variables:
- my-disabled-variable
- also-called-placeholders
