#      TimeLock Example Configuration
# ----------------------------------------
# Refresh-Rate: 5 (how often TimeLock will reset the time, in seconds)
# World:     
#   world: day
#   world_nether: night
#   world_the_end: normal
Refresh-Rate: 5
World:
<<<<<<< HEAD
  spawn: day
=======
  spawn: night
>>>>>>> 46ada2d94dc03a579d13f3eb4061a67081594a09
  plotworld: normal
  mines: night
  parkour: night
  free: normal
  world_the_end: night
