version: 3.1.9
schematics:
  save_path: /home/minecraft/plugins/PlotSquared/schematics
chunk-processor:
  enabled: false
  max-entities: 512
  max-blockstates: 4096
  disable-physics: false
  experimental-fast-async-worldedit: false
  auto-unload: false
  auto-trim: false
uuid:
  read-from-disk: false
  use_sqluuidhandler: false
claim:
  max-auto-area: 4
clear:
  fastmode: false
  auto:
    enabled: false
    days: 365
    clear-interval-seconds: 120
    threshold: -1
    calibration:
      changes_sd: 64
      variety_sd: 1
      faces_sd: 32
      air: 0
      faces: 2
      changes: 1
      data_sd: 1
      variety: 1
      air_sd: 0
      data: 32
  check-disk: false
  'on':
    ban: false
max_plots: 64
console:
  color: true
teleport:
  on_login: false
  delay: 0
debug: false
clusters:
  enabled: false
auto_update: false
plotme-convert:
  enabled: false
  cache-uuids: false
confirmation:
  unlink: true
  delete: true
  clear: true
kill_road_mobs: false
metrics: true
cache:
  permissions: false
  ratings: true
plotme-alias: false
worldedit:
  max-iterations: 1000
  max-volume: 500000
  blacklist:
  - cs
  - .s
  - restore
  - snapshot
  - delchunks
  - listchunks
  require-selection-in-mask: true
  enable-for-helpers: false
  queue-commands: false
comments:
  notifications:
    enabled: false
mob_pathfinding: true
UUID:
  force-lowercase: false
  offline: false
protection:
  tnt-listener:
    enabled: false
  piston:
    falling-blocks: true
  physics-listener:
    enabled: false
  redstone:
    disable-offline: false
    disable-unoccupied: false
titles: false
global_limit: false
worlds:
  plotworld:
    road:
      width: 5
      block: '112'
      height: 64
    plot:
      size: 11
      floor:
      - '2'
      filling:
      - '3'
      height: 64
      biome: FOREST
      bedrock: true
      create_signs: false
      auto_merge: true
    wall:
      block: '44:7'
      height: 64
      filling: '1:0'
      block_claimed: '44:1'
    event:
      spawn:
        breeding: false
        egg: true
        custom: true
      pvp: false
      pve: false
    economy:
      use: false
      prices:
        claim: 10000.0
        sell: 7500.0
        merge: 1000000.0
    home:
      allow-nonmembers: false
      default: side
    world:
      border: false
      max_height: 256
      gamemode: creative
      min_height: 1
    schematic:
      file: 'null'
      on_claim: false
      specify_on_claim: false
    chat:
      enabled: false
    flags: {}
    natural_mob_spawning: false
    limits:
      max-members: 128
  world_creative:
    road:
      width: 5
      block: '112'
      height: 64
    plot:
      size: 65
      floor:
      - '2'
      filling:
      - '3'
      height: 64
      biome: FOREST
      bedrock: true
      create_signs: false
      auto_merge: true
    wall:
      block: '44:7'
      height: 64
      filling: '1:0'
      block_claimed: '44:1'
    event:
      spawn:
        breeding: false
        egg: false
        custom: true
      pvp: false
      pve: false
    economy:
      use: false
      prices:
        claim: 100.0
        sell: 75.0
        merge: 100.0
    home:
      allow-nonmembers: false
      default: side
    world:
      border: false
      max_height: 256
      gamemode: creative
      min_height: 1
    schematic:
      file: 'null'
      on_claim: false
      specify_on_claim: false
    chat:
      enabled: false
    flags: {}
    natural_mob_spawning: false
    limits:
      max-members: 128
chat:
  fancy: true
web:
  server-ip: mc.rockdiamond.net
  url: http://empcraft.com/plots/
platform: Bukkit
update-notifications: true
approval:
  done:
    counts-towards-limit: false
    restrict-building: false
    required-for-download: false
  ratings:
    require-done: false
kill_road_vehicles: true
bo3:
  save_path: BO3
